<?php

namespace App\Services\ImportacaoAssistida\Readers;

use App\Services\ImportacaoAssistida\DTOs\RegistroDto;
use RuntimeException;

/**
 * Parses one page of Super_Simples.pdf.
 *
 * Standard layout (Layout A): 20 faixa rows per page.
 *   Rows  0–9  → NOSSO MÉDICO  (plano_id = 24)
 *   Rows 10–19 → NOSSO PLANO   (plano_id = 5)
 *
 * Column order per faixa row (4 values — no ambulatorial):
 *   idx 0: ENF  – CopParcial (copat=0)
 *   idx 1: APT  – CopParcial (copat=0)
 *   idx 2: ENF  – CopTotal   (copat=1)
 *   idx 3: APT  – CopTotal   (copat=1)
 *
 * Column order per faixa row (6 values — with S/ACOM column):
 *   idx 0: S/ACOM – CopParcial (copat=0, acomodacao_id=3)
 *   idx 1: ENF    – CopParcial (copat=0)
 *   idx 2: APT    – CopParcial (copat=0)
 *   idx 3: S/ACOM – CopTotal   (copat=1, acomodacao_id=3)
 *   idx 4: ENF    – CopTotal   (copat=1)
 *   idx 5: APT    – CopTotal   (copat=1)
 *
 * Header confirmed: "ACOMODAÇÃO: S/ ACOM  ENFERM  APART | S/ ACOM  ENFERM  APART"
 *
 * Odonto: the PDF always shows Sem Odonto values (odonto=0).
 *   odonto=1 rows are generated by adding valorPromo to every non-zero value.
 *   valorPromo is extracted from the PREMIUM NACIONAL line (last monetary value).
 *
 * ── Layout with Pleno (e.g. Sertãozinho) — 3 tables, 30 faixa rows total ───
 *   Appear in this order: NOSSO MÉDICO, NOSSO PLANO, PLENO (plano_id = 11).
 *   Each table is independently COLS_4 or COLS_6 (detected per block, same
 *   as the 20-row layout) — no skip columns, no embedded promo/odonto extras.
 */
class SuperSimplesReader
{
    const PLANO_SUPER_SIMPLES    = 5;
    const PLANO_SS_NOSSO_MEDICO  = 24;
    const PLANO_SS_PLENO         = 11;

    private const ACOM_ENFERMARIA   = 2;
    private const ACOM_APARTAMENTO  = 1;
    private const ACOM_AMBULATORIAL = 3;

    private const FAIXAS_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

    private const COLS_4 = [
        0 => ['acom' => self::ACOM_ENFERMARIA,  'copat' => 0],
        1 => ['acom' => self::ACOM_APARTAMENTO, 'copat' => 0],
        2 => ['acom' => self::ACOM_ENFERMARIA,  'copat' => 1],
        3 => ['acom' => self::ACOM_APARTAMENTO, 'copat' => 1],
    ];

    private const COLS_6 = [
        0 => ['acom' => self::ACOM_AMBULATORIAL, 'copat' => 0],  // S/ACOM copat=0
        1 => ['acom' => self::ACOM_ENFERMARIA,   'copat' => 0],  // ENF    copat=0
        2 => ['acom' => self::ACOM_APARTAMENTO,  'copat' => 0],  // APT    copat=0
        3 => ['acom' => self::ACOM_AMBULATORIAL, 'copat' => 1],  // S/ACOM copat=1
        4 => ['acom' => self::ACOM_ENFERMARIA,   'copat' => 1],  // ENF    copat=1
        5 => ['acom' => self::ACOM_APARTAMENTO,  'copat' => 1],  // APT    copat=1
    ];

    /**
     * @return RegistroDto[]
     * @throws RuntimeException
     */
    public function parse(string $pageText): array
    {
        $valorPromo = $this->extractValorPromo($pageText);
        $allRows    = $this->extractAllFaixaRows($pageText);
        $count      = count($allRows);

        if ($count === 20) {
            $medicoRows = array_values(array_slice($allRows, 0, 10));
            $planoRows  = array_values(array_slice($allRows, 10, 10));

            $medicoCols = count($medicoRows[0] ?? []) >= 6 ? self::COLS_6 : self::COLS_4;
            $planoCols  = count($planoRows[0]  ?? []) >= 6 ? self::COLS_6 : self::COLS_4;

            return array_merge(
                $this->buildRegistros(self::PLANO_SS_NOSSO_MEDICO, $medicoCols, $medicoRows, $valorPromo),
                $this->buildRegistros(self::PLANO_SUPER_SIMPLES,   $planoCols,  $planoRows,  $valorPromo),
            );
        }

        if ($count === 10) {
            $cols    = count($allRows[0] ?? []) >= 6 ? self::COLS_6 : self::COLS_4;
            $planoId = $this->detectSinglePlanId($pageText);
            return $this->buildRegistros($planoId, $cols, $allRows, $valorPromo);
        }

        if ($count === 30) {
            [$medicoRows, $planoRows, $plenoRows] = array_chunk($allRows, 10);

            $medicoCols = count($medicoRows[0] ?? []) >= 6 ? self::COLS_6 : self::COLS_4;
            $planoCols  = count($planoRows[0]  ?? []) >= 6 ? self::COLS_6 : self::COLS_4;
            $plenoCols  = count($plenoRows[0]  ?? []) >= 6 ? self::COLS_6 : self::COLS_4;

            return array_merge(
                $this->buildRegistros(self::PLANO_SS_NOSSO_MEDICO, $medicoCols, $medicoRows, $valorPromo),
                $this->buildRegistros(self::PLANO_SUPER_SIMPLES,   $planoCols,  $planoRows,  $valorPromo),
                $this->buildRegistros(self::PLANO_SS_PLENO,        $plenoCols,  $plenoRows,  $valorPromo),
            );
        }

        throw new RuntimeException(
            sprintf('Super Simples: esperado 10, 20 ou 30 faixas, encontrado %d.', $count)
        );
    }

    /**
     * Detects which single plan is on the page (used when only 10 faixa rows are found).
     * Searches for spaced-out "NOSSO MÉDICO" label; falls back to NOSSO PLANO.
     */
    private function detectSinglePlanId(string $text): int
    {
        if (preg_match('/N\s*O\s*S\s*S\s*O\s+M\s*[ÉE]\s*D\s*I\s*C\s*O/ui', $text)) {
            return self::PLANO_SS_NOSSO_MEDICO;
        }
        return self::PLANO_SUPER_SIMPLES;
    }

    // ─── Internals ─────────────────────────────────────────────────────────

    /** @return RegistroDto[] */
    private function buildRegistros(int $planoId, array $colDefs, array $faixaRows, float $valorPromo): array
    {
        $registros = [];

        foreach ([0, 1] as $odonto) {
            foreach ($colDefs as $colIdx => $def) {
                foreach (self::FAIXAS_IDS as $faixaIdx => $faixaId) {
                    $valor = $faixaRows[$faixaIdx][$colIdx] ?? 0.0;

                    if ($odonto === 1 && $valorPromo > 0 && $valor > 0) {
                        $valor = round($valor + $valorPromo, 2);
                    }

                    $registros[] = new RegistroDto(
                        planoId:        $planoId,
                        acomodacaoId:   $def['acom'],
                        faixaEtariaId:  $faixaId,
                        coparticipacao: $def['copat'],
                        odonto:         $odonto,
                        valorPdf:       round($valor, 2),
                    );
                }
            }
        }

        return $registros;
    }

    private function extractValorPromo(string $text): float
    {
        // Last monetary value on the PREMIUM NACIONAL line.
        if (preg_match('/PREMIUM\s*NACIONAL[^\n]+/u', $text, $m)) {
            preg_match_all('/\b(\d{1,3}(?:\.\d{3})*,\d{2})\b(?!\s*%)/u', $m[0], $vals);
            if (!empty($vals[1])) {
                $last = end($vals[1]);
                return (float) str_replace(['.', ','], ['', '.'], $last);
            }
        }

        return 0.0;
    }

    /**
     * @return array<int, float[]>
     */
    private function extractAllFaixaRows(string $text): array
    {
        preg_match_all(
            '/(?:\d{1,2}\s*[Aa]\s*\d{1,2}\s*[Aa][Nn][Oo][Ss]|59\s*[Aa][Nn][Oo][Ss]\s*[Oo][Uu]\s*[Mm][Aa][Ii][Ss])([^\n]*)/u',
            $text,
            $matches,
            PREG_SET_ORDER,
        );

        $rows = [];
        foreach ($matches as $match) {
            $values = $this->extractMonetaryValues($match[0]);
            if (!empty($values)) {
                $rows[] = $values;
            }
        }

        return $rows;
    }

    /** @return float[] */
    private function extractMonetaryValues(string $text): array
    {
        preg_match_all('/\b(\d{1,3}(?:\.\d{3})*,\d{2})\b(?!\s*%)/u', $text, $m);

        return array_map(
            fn($v) => (float) str_replace(['.', ','], ['', '.'], $v),
            $m[1],
        );
    }
}
